### ISSUE TITLE
Old Node Version

### ISSUE THREAD

**Issue by ReshmiCode** [bZichett/jest-retry#6]
When trying to add the package from npm I'm getting an error:
error jest-retry@1.0.21: The engine "node" is incompatible with this module. Expected version "8.9.1". Got "10.15.3"
error Found incompatible module.

Is it possible to update this? I know this capability was added in jest-circus but I can't use that in my project.

**Comment by bZichett** [comment]
I just removed the hard engine dependency (dont think I required anything special about 8.9.1)

I also pushed to npm registry under `jest-retry-module@1.0.24`.

Let me know if I can help anymore =)

**Comment by ReshmiCode** [comment]
@bZichett the setup is a bit vague. I have both unit tests and end to end tests (Detox with Jest as the test runner). My main goal is to see if it can work with my e2e tests but I thought I'd make sure it works with my unit tests first.
Am I supposed to just make a file in the root directory with the stuff from sample code? My unit tests are spread out across other subfolders in the src folder.
