### ISSUE TITLE
Documentation Vague for Setup

### ISSUE THREAD

**Issue by ReshmiCode** [bZichett/jest-retry#7]
The documentation setup is a bit vague. I have both unit tests and end to end tests (Detox with Jest as the test runner). My main goal is to see if it can work with my e2e tests but I thought I'd make sure it works with my unit tests first.
Am I supposed to just make a file in the root directory with the code from `example run`? My unit tests are spread out across other subfolders in the src folder so would testDir just be src/? I'm also not sure what all the configurations are / which ones are not required.

**Comment by harpet06** [comment]
Yeah, also not clear on how to set this up.. any further docs would be appreciated

**Comment by andreabisello** [comment]
@ReshmiCode have you found the way to use or alternative plugin?

**Comment by bZichett** [comment]
@andreabisello, @ReshmiCode, @harpet06 Were any of you able to at least get the unit test suite working as intended?  I can add more documentation, but if you get the tests working, it should be straightforward how to use the same pattern in your own code base? 

 It is intended to be as simple as:
`jestRetry(runConfig)` (as seen in `run.js` in test directory - https://github.com/bZichett/jest-retry/blob/master/test/run.js)

**Comment by andreabisello** [comment]
@bZichett  jestRetry is a new command line that will be avaiable after the installation of the npm jest-retry ? i runs command like

`jest --testFailureExitCode 0 --setupFiles=./configurazioni/integration-configuration.js --verbose
`
how should i have to use jestRetry with this command line?

thanks for your work and your suggestion

**Comment by bZichett** [comment]
I dont believe I added jest-retry to node_modules/.bin, so I dont think it'll work from command line.  Try creating a script similar to test.js and run it via `node test.js`

That being said, if you are using npm 5.2+, `npx jest-retry` may work via command line.

**Comment by ReshmiCode** [comment]
@andreabisello I ended up using the jest-circus runner

**Comment by bZichett** [comment]
I wrote jest-retry when jest-circus was being implemented.  If it were me, I'd use that if it doesnt cause much trouble
